version: "3.8"

services:
  pharita-bot:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: pharita_news_bot
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - ../data:/app/data
      - telethon_session:/app/session

volumes:
  telethon_session:
